# 游낈 ICT ENGINE v6.0 ENTERPRISE - PRODUCTION CONFIGURATION
# =======================================================
# Configuraci칩n espec칤fica para entorno de producci칩n

# 游늵 TRADING CONFIGURATION (Production overrides)
trading:
  # Configuraci칩n m치s conservadora para producci칩n
  max_positions: 3
  max_daily_trades: 10
  risk_per_trade: 0.015  # 1.5% por operaci칩n (m치s conservador)
  
  # Order blocks - configuraci칩n optimizada
  order_blocks:
    min_size_pips: 15  # M치s estricto en producci칩n
    max_age_hours: 12  # M치s reciente
    detection_timeframes: ["H1", "H4"]  # Solo timeframes principales

# 游댋 MT5 CONNECTION (Production)
mt5:
  connection:
    timeout: 30000  # 30 seconds (m치s r치pido)
    retries: 5      # M치s reintentos
    retry_delay: 3  # Menos delay
  
  # Production server details (to be set via environment variables)
  # ICT_CONFIG_MT5_CONNECTION_SERVER
  # ICT_CONFIG_MT5_CONNECTION_LOGIN
  # ICT_CONFIG_MT5_CONNECTION_PASSWORD

# 游꿢 RISK MANAGEMENT (Production)
risk:
  # L칤mites m치s estrictos para producci칩n
  emergency_drawdown_limit: 0.05  # 5% (m치s conservador)
  max_consecutive_losses: 3       # Menos p칠rdidas consecutivas
  daily_loss_limit: 0.03         # 3% (m치s conservador)
  
  position_sizing:
    method: "fixed_risk"
    max_position_size: 5.0  # M치s conservador

# 游늳 DASHBOARD CONFIGURATION (Production)
dashboard:
  refresh_interval: 10000  # 10 seconds (menos frecuente)
  
  charts:
    max_candles: 500        # Menos datos para performance
    update_interval: 5000   # 5 seconds

# 游닇 LOGGING CONFIGURATION (Production)
logging:
  level: "WARNING"  # Solo warnings y errores
  
  rotation:
    max_size_mb: 50   # Archivos m치s peque침os
    backup_count: 10  # M치s backups
  
  # Solo logs cr칤ticos en producci칩n
  categories:
    trading: true
    mt5: true
    dashboard: false  # Deshabilitado para performance
    order_blocks: true
    patterns: false   # Deshabilitado para performance
    risk: true
    system: true

# 游댢 SYSTEM CONFIGURATION (Production)
system:
  performance:
    cache_ttl_seconds: 600  # 10 minutes (m치s cache)
    max_memory_usage_mb: 512  # Menos memoria
    cleanup_interval_minutes: 10  # M치s frecuente
  
  health:
    check_interval_seconds: 15  # M치s frecuente
    alert_thresholds:
      cpu_percent: 70      # M치s estricto
      memory_percent: 75   # M치s estricto
      disk_percent: 85     # M치s estricto
  
  persistence:
    backup_interval_hours: 2  # Backups m치s frecuentes
    retention_days: 90       # M치s retenci칩n

# 游뚿 ALERTS CONFIGURATION (Production)
alerts:
  channels:
    console: false      # Deshabilitado en producci칩n
    file: true
    dashboard: true
    email: true         # Habilitado para producci칩n
  
  # Todos los tipos habilitados para producci칩n
  types:
    order_block_detected: true
    pattern_confirmed: true
    risk_threshold_exceeded: true
    system_error: true
    mt5_connection_lost: true

# 游댏 SECURITY CONFIGURATION
security:
  # Configuraci칩n de seguridad para producci칩n
  encrypt_logs: true
  audit_trail: true
  session_timeout_minutes: 30
  
  # Rate limiting
  rate_limits:
    api_calls_per_minute: 100
    dashboard_requests_per_minute: 60
    
# 游늵 PERFORMANCE MONITORING
monitoring:
  # M칠tricas adicionales para producci칩n
  enabled: true
  collect_system_metrics: true
  collect_trading_metrics: true
  
  # Reporting
  daily_reports: true
  weekly_reports: true
  monthly_reports: true